#!/bin/sh


VER="2.0.1"

echo "Creating tar.gz file"
git archive --format=tar --prefix=bulbcalculator-$VER/ master | gzip > ../bulbcalculator-src-$VER.tar.gz

echo "Creating tar.xz file"
git archive --format=tar --prefix=bulbcalculator-$VER/ master | xz > ../bulbcalculator-src-$VER.tar
xz ../bulbcalculator-src-$VER.tar
